### ISSUE TITLE
Coredump on start, CentOS 9 Stream

### ISSUE THREAD

**Issue by alexandrustinov** [xeco23/WasIstLos#290]
**Description**
Coredump on start, CentOS 9 Stream

**To Reproduce**
Execute ./whatsapp-for-linux-1.6.2-x86_64.AppImage

**Environment**
CentOS 9 Stream, Kernel 6.1.27-1.el9.elrepo.x86_64, Gnome Standard session, Wayland 

Here the tail of `strace ./whatsapp-for-linux-1.6.2-x86_64.AppImage`

    clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7f7d4a7fa910, parent_tid=0x7f7d4a7fa910, exit_signal=0, stack
    =0x7f7d49ffa000, stack_size=0x7ffbc0, tls=0x7f7d4a7fa640} => {parent_tid=[31089]}, 88) = 31089
    rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
    sched_setscheduler(31089, 0x40000000 /* SCHED_??? */, [0]) = 0
    sched_getaffinity(31089, 32, [0, 1, 2, 3]) = 8
    futex(0x7f7d9c5e4068, FUTEX_WAKE_PRIVATE, 1) = 1
    futex(0x7f7db013e78c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    openat(AT_FDCWD, "/dev/urandom", O_RDONLY) = 29
    read(29, "\274\37\221\225H\223q7\nF\240\370T\203\0334", 16) = 16
    close(29)                               = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f7d497f9000
    mprotect(0x7f7d497fa000, 8388608, PROT_READ|PROT_WRITE) = 0
    rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
    clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7f7d49ff9910, parent_tid=0x7f7d49ff9910, exit_signal=0, stack
    =0x7f7d497f9000, stack_size=0x7ffbc0, tls=0x7f7d49ff9640} => {parent_tid=[31090]}, 88) = 31090
    rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    madvise(0x7f7d9c5de000, 4096, MADV_NORMAL) = 0
    madvise(0x7f7d9c5de000, 4096, MADV_DODUMP) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    openat(AT_FDCWD, "/etc/machine-info", O_RDONLY) = -1 ENOENT (No such file or directory)
    openat(AT_FDCWD, "/sys/class/dmi/id/chassis_type", O_RDONLY) = 29
    newfstatat(29, "", {st_mode=S_IFREG|0444, st_size=4096, ...}, AT_EMPTY_PATH) = 0
    read(29, "3\n", 4096)                   = 2
    read(29, "", 4094)                      = 0
    close(29)                               = 0
    futex(0x7f7db0143280, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    uname({sysname="Linux", nodename="desk.intranet", ...}) = 0
    madvise(0x7f7d9c5dd000, 4096, MADV_NORMAL) = 0
    madvise(0x7f7d9c5dd000, 4096, MADV_DODUMP) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f7d48ff8000
    mprotect(0x7f7d48ff9000, 8388608, PROT_READ|PROT_WRITE) = 0
    rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
    clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7f7d497f8910, parent_tid=0x7f7d497f8910, exit_signal=0, stack
    =0x7f7d48ff8000, stack_size=0x7ffbc0, tls=0x7f7d497f8640} => {parent_tid=[31091]}, 88) = 31091
    rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
    sched_setscheduler(31091, 0x40000000 /* SCHED_??? */, [0]) = 0
    sched_getaffinity(31091, 32, [0, 1, 2, 3]) = 8
    futex(0x7f7d9c5f8460, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = 0
    futex(0x7f7d9c5f8410, FUTEX_WAKE_PRIVATE, 1) = 0
    futex(0x7f7ce0000b70, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
    write(30, "\1\0\0\0\0\0\0\0", 8)        = 8
    futex(0x7f7ce0000b70, FUTEX_WAKE_PRIVATE, 1) = 1
    mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f7d487f7000
    mprotect(0x7f7d487f8000, 8388608, PROT_READ|PROT_WRITE) = 0
    rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
    clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7f7d48ff7910, parent_tid=0x7f7d48ff7910, exit_signal=0, stack
    =0x7f7d487f7000, stack_size=0x7ffbc0, tls=0x7f7d48ff7640} => {parent_tid=[31092]}, 88) = 31092
    rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
    sched_setscheduler(31092, 0x40000000 /* SCHED_??? */, [0]) = 0
    sched_getaffinity(31092, 32, [0, 1, 2, 3]) = 8
    futex(0x7f7d9c5e42a8, FUTEX_WAKE_PRIVATE, 1) = 1
    futex(0x7f7d9c5f8464, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = 0
    futex(0x7f7d9c5f8410, FUTEX_WAKE_PRIVATE, 1) = 0
    madvise(0x7f7d9c5d4000, 4096, MADV_NORMAL) = 0
    madvise(0x7f7d9c5d4000, 4096, MADV_DODUMP) = 0
    socketpair(AF_UNIX, SOCK_SEQPACKET, 0, [32, 33]) = 0
    fcntl(33, F_GETFD)                      = 0
    fcntl(33, F_SETFD, FD_CLOEXEC)          = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    openat(AT_FDCWD, "/dev/null", O_RDONLY|O_CLOEXEC) = 34
    prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=512*1024}) = 0
    prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=512*1024}) = 0
    fcntl(32, F_DUPFD_CLOEXEC, 33)          = 35
    prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=512*1024}) = 0
    prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=512*1024}) = 0
    mmap(NULL, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f7d9c1e7000
    rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
    clone3({flags=CLONE_VM|CLONE_VFORK, exit_signal=SIGCHLD, stack=0x7f7d9c1e7000, stack_size=0x9000}, 88) = 31093
    wait4(31093, NULL, 0, NULL)             = 31093
    munmap(0x7f7d9c1e7000, 36864)           = 0
    rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
    close(34)                               = 0
    close(35)                               = 0
    getpeername(2, 0x7ffdf2c6b980, [128])   = -1 ENOTSOCK (Socket operation on non-socket)
    futex(0x7f7db4c270a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    ioctl(2, TCGETS, 0x7ffdf2c6b950)        = -1 ENOTTY (Inappropriate ioctl for device)
    getpid()                                = 31069
    openat(AT_FDCWD, "/etc/localtime", O_RDONLY|O_CLOEXEC) = 34
    newfstatat(34, "", {st_mode=S_IFREG|0644, st_size=3497, ...}, AT_EMPTY_PATH) = 0
    newfstatat(34, "", {st_mode=S_IFREG|0644, st_size=3497, ...}, AT_EMPTY_PATH) = 0
    read(34, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\f\0\0\0\f\0\0\0\0"..., 4096) = 3497
    lseek(34, -2210, SEEK_CUR)              = 1287
    read(34, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\f\0\0\0\f\0\0\0\0"..., 4096) = 2210
    close(34)                               = 0
    write(2, "\n** (whatsapp-for-linux:31069): "..., 219) = -1 EPIPE (Broken pipe)
    --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=31069, si_uid=1000} ---
    --- SIGTRAP {si_signo=SIGTRAP, si_code=SI_KERNEL} ---
    +++ killed by SIGTRAP (core dumped) +++
    Trace/breakpoint trap

**Comment by alexandrustinov** [comment]
coredump is attached
[whatsapp-for-li_core_dump.gz](https://github.com/eneshecan/whatsapp-for-linux/files/11453108/whatsapp-for-li_core_dump.gz)

**Comment by eneshecan** [comment]
We have a problem with our AppImage package regarding webkit. Please see #160.
