### ISSUE TITLE
Tray icon: show/hide on single click

### ISSUE THREAD

**Issue by gersonjferreira** [xeco23/WasIstLos#387]
**Is your feature request related to a problem? Please describe.**
To show the window out of the tray, we need to click on the icon and then on "Show". It would be better to show/hide on single click direct on the icon.

**Describe the solution you'd like**
This happens pretty much with many apps on tray for Gnome and I don't know if it is a limitation or design flaw. At the moment for me, it happens with whatsapp-for-linux, Zulip and Insync. But for the flameshot app, the single direct click on the tray icon opens the app directly without the need of a submenu. So, there's a way to fix this, but I don't know what are the hidden issues that makes this difficult.

**Comment by xeco23** [comment]
Please see #140
