### ISSUE TITLE
Rename the application

### ISSUE THREAD

**Issue by rijnhard** [xeco23/WasIstLos#399]
**Description**
The app has been delisted from Flathub

**To Reproduce**
1. Go to ['flathub'](https://flathub.org/apps/com.github.eneshecan.WhatsAppForLinux)
2. See the error

**Expected behavior**
Should not be delisted

**Screenshots**
![Screenshot](https://github.com/user-attachments/assets/f562b84b-ed44-47e4-a6a0-f3badfd0b949)

**Environment**
 - Distro: Fedora 40 (KDE)
 - Package: flatpak (flathub)
 - Desktop Environment: KDE

**Comment by Pryka** [comment]
It won't come back - https://github.com/flathub/com.github.eneshecan.WhatsAppForLinux/issues/14

**Comment by winstonma** [comment]
Does it mean that the name of the app need to be changed in order to get back to flathub?

**Comment by James-Oakley** [comment]
Looking at the linked issue, I can see that @eneshecan doesn't wish to rename the app. I'm wondering why renaming it is so bad that delisting would be preferred.

**Comment by goldyfruit** [comment]
On my side, if the application is not listed on Flathub then I'm not gonna use it anymore _(which will be a shame)_.

**Comment by eneshecan** [comment]
I am not completely against renaming but it needs a bit of time and effort which I don't have these days. Yet I am also unable to come up with a good name. If you guys can propose a good name, we can rename it :) After that, it would be nice to have someone maintaining the flatpak package again.

**Comment by rijnhard** [comment]
Can copy what the teams app did?

Portal for WhatsApp?

**Comment by eneshecan** [comment]
I think they wouldn't like if we keep `WhatsApp` in the name

**Comment by eneshecan** [comment]
> I second the name 'Portal for WhatsApp'.

Well, I think this also goes against the naming policy of flatpak since it includes `WhatsApp`...

**Comment by colonia-duck** [comment]
> Well, I think this also goes against the naming policy of flatpak since it includes `WhatsApp`. We need something more creative.

ah yes that maybe a problem.

**Comment by rijnhard** [comment]
@bbhtt @barthalion would "Portal for WhatsApp" be acceptable?

**Comment by bbhtt** [comment]
Yes that's fine although preferably you can come up with your own distinct name like Whatsie or Youp which would be even better.

The other issue is having its own distinct icon https://raw.githubusercontent.com/eneshecan/whatsapp-for-linux/master/resource/image/icons/hicolor/256x256/apps/com.github.eneshecan.WhatsAppForLinux.png looks like a recoloured version of the official icon.

See the icon included in https://about.meta.com/brand/resources/whatsapp/whatsapp-brand/ -> Glyph -> Digital -> SVG -> Green

**Comment by stklcode** [comment]
Suggestion: Rebuild a balloon out of two simple shapes and add a keyboard instead of phone icon (the "app" is designed to use on computers, not phones) and keep the green:

<img src="https://github.com/user-attachments/assets/191bad89-636f-48d7-9ad4-e0255c353162" alt="icon" width="64">
<img src="https://github.com/user-attachments/assets/191bad89-636f-48d7-9ad4-e0255c353162" alt="icon" width="32">
<img src="https://github.com/user-attachments/assets/191bad89-636f-48d7-9ad4-e0255c353162" alt="icon" width="16">

<img src="https://github.com/user-attachments/assets/fca0dd3e-7b97-435a-9c8e-fe78351a9467" alt="icon-attention" width="64">
<img src="https://github.com/user-attachments/assets/fca0dd3e-7b97-435a-9c8e-fe78351a9467" alt="icon-attention" width="32">
<img src="https://github.com/user-attachments/assets/fca0dd3e-7b97-435a-9c8e-fe78351a9467" alt="icon-attention" width="16">

<br>
<br>

I don't really like the pale color (but that's personal taste), so maybe switch _LimeGreen_ ...

<img src="https://github.com/user-attachments/assets/4d394791-3fa9-4b2f-9c28-9934108a0b0b" alt="icon-attention" width="64">
<img src="https://github.com/user-attachments/assets/4d394791-3fa9-4b2f-9c28-9934108a0b0b" alt="icon-attention" width="32">
<img src="https://github.com/user-attachments/assets/4d394791-3fa9-4b2f-9c28-9934108a0b0b" alt="icon-attention" width="16">

<img src="https://github.com/user-attachments/assets/ff7b8091-5f22-4106-bee8-9197aff5a794" alt="icon" width="64">
<img src="https://github.com/user-attachments/assets/ff7b8091-5f22-4106-bee8-9197aff5a794" alt="icon" width="32">
<img src="https://github.com/user-attachments/assets/ff7b8091-5f22-4106-bee8-9197aff5a794" alt="icon" width="16">

<br>
<br>

For reference, the original WhatsApp logo a same scale

<img src="https://github.com/user-attachments/assets/dbba6f42-7e4e-4fc9-bc61-4895d49feae8" alt="WhatsApp" width="64">
<img src="https://github.com/user-attachments/assets/dbba6f42-7e4e-4fc9-bc61-4895d49feae8" alt="WhatsApp" width="32">
<img src="https://github.com/user-attachments/assets/dbba6f42-7e4e-4fc9-bc61-4895d49feae8" alt="WhatsApp" width="16">

<br>
<br>

Feel free to use either (of the custom versions of course) at project license.

**Comment by rijnhard** [comment]
Re the name, just to avoid containing WhatsApp.

* WhatUp
* ChatUp
* GreenUp
* WA Desktop
* at this point I'm just dumping bad names 😅

I think ir @eneshecan is fine with living in the grey area then Portal for WhatsApp with the new icon. 

And we ready to rock.

**Comment by eylenburg** [comment]
Would another alternative be to host a Flatpak "repo" (with just 1 app) yourself? It would still be useful for people on Flatpak-first systems like Fedora Atomic or OpenSUSE MicroOS.

**Comment by stklcode** [comment]
No capacity to change the name, but host another repo... :thinking: 

Besides that, the actual issue is trademark rights / usage terms of the name WhatsApp and logo and this would apply if hosted on a different repository, just shifts the accountability.

**Comment by xeco23** [comment]
Okay, I renamed the app to `WasIstLos` since I didn't want to wait no more and it was in my mind for quite a while. Please consider reporting some forgotten things or create a PR.

Anyone is welcome to to submit a flatpak repo and maintain please refer to the old one https://github.com/flathub/com.github.eneshecan.WhatsAppForLinux

**Comment by xeco23** [comment]
> Suggestion: Rebuild a balloon out of two simple shapes and add a keyboard instead of phone icon (the "app" is designed to use on computers, not phones) and keep the green:
> <img alt="icon" width="64" src="https://private-user-images.githubusercontent.com/12963621/374241301-191bad89-636f-48d7-9ad4-e0255c353162.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDEzMDEtMTkxYmFkODktNjM2Zi00OGQ3LTlhZDQtZTAyNTVjMzUzMTYyLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZTVmYThhOTQwMzdhNmZhN2E1ZmJiNmNlNjJkNzZmOTQ3YTFjYTc4NTM1ZTY3MWE1NjEzNTk2YjkyMzA4MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.87vKCVi7FJoOMbcC4FF3inw1an7Kq-s0-FTUtnRzQ6M"> <img alt="icon" width="32" src="https://private-user-images.githubusercontent.com/12963621/374241301-191bad89-636f-48d7-9ad4-e0255c353162.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDEzMDEtMTkxYmFkODktNjM2Zi00OGQ3LTlhZDQtZTAyNTVjMzUzMTYyLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZTVmYThhOTQwMzdhNmZhN2E1ZmJiNmNlNjJkNzZmOTQ3YTFjYTc4NTM1ZTY3MWE1NjEzNTk2YjkyMzA4MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.87vKCVi7FJoOMbcC4FF3inw1an7Kq-s0-FTUtnRzQ6M"> <img alt="icon" width="16" src="https://private-user-images.githubusercontent.com/12963621/374241301-191bad89-636f-48d7-9ad4-e0255c353162.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDEzMDEtMTkxYmFkODktNjM2Zi00OGQ3LTlhZDQtZTAyNTVjMzUzMTYyLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZTVmYThhOTQwMzdhNmZhN2E1ZmJiNmNlNjJkNzZmOTQ3YTFjYTc4NTM1ZTY3MWE1NjEzNTk2YjkyMzA4MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.87vKCVi7FJoOMbcC4FF3inw1an7Kq-s0-FTUtnRzQ6M"> <img alt="icon-attention" width="64" src="https://private-user-images.githubusercontent.com/12963621/374241311-fca0dd3e-7b97-435a-9c8e-fe78351a9467.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDEzMTEtZmNhMGRkM2UtN2I5Ny00MzVhLTljOGUtZmU3ODM1MWE5NDY3LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0OGExY2VhYzliM2Q2YWVlOTJlNjViNjk3YzMyYjJiZjZjOTU5NzQyODZhMDMwZjAzZjg4NjY5MjFjYzc1YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fJ3gtsQ52OFRgTeoUQCZ3KZZW9jKVJpnWfJS9Cc7Bl8"> <img alt="icon-attention" width="32" src="https://private-user-images.githubusercontent.com/12963621/374241311-fca0dd3e-7b97-435a-9c8e-fe78351a9467.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDEzMTEtZmNhMGRkM2UtN2I5Ny00MzVhLTljOGUtZmU3ODM1MWE5NDY3LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0OGExY2VhYzliM2Q2YWVlOTJlNjViNjk3YzMyYjJiZjZjOTU5NzQyODZhMDMwZjAzZjg4NjY5MjFjYzc1YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fJ3gtsQ52OFRgTeoUQCZ3KZZW9jKVJpnWfJS9Cc7Bl8"> <img alt="icon-attention" width="16" src="https://private-user-images.githubusercontent.com/12963621/374241311-fca0dd3e-7b97-435a-9c8e-fe78351a9467.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDEzMTEtZmNhMGRkM2UtN2I5Ny00MzVhLTljOGUtZmU3ODM1MWE5NDY3LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0OGExY2VhYzliM2Q2YWVlOTJlNjViNjk3YzMyYjJiZjZjOTU5NzQyODZhMDMwZjAzZjg4NjY5MjFjYzc1YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fJ3gtsQ52OFRgTeoUQCZ3KZZW9jKVJpnWfJS9Cc7Bl8">
> 
> I don't really like the pale color (but that's personal taste), so maybe switch _LimeGreen_ ...
> <img alt="icon-attention" width="64" src="https://private-user-images.githubusercontent.com/12963621/374245590-4d394791-3fa9-4b2f-9c28-9934108a0b0b.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDU1OTAtNGQzOTQ3OTEtM2ZhOS00YjJmLTljMjgtOTkzNDEwOGEwYjBiLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhOTMzMmVkNzNkZTkzMmQxYTg3NjI0M2MxOTlkODkzOTBmMDJlOGQzOGJlYjI4MzYyMDcyMzA4NTQ3NWUwMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uVl-htjj2s2mXbo_PuIWeefiGSHeLrEJ80rxDFpAxfc"> <img alt="icon-attention" width="32" src="https://private-user-images.githubusercontent.com/12963621/374245590-4d394791-3fa9-4b2f-9c28-9934108a0b0b.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDU1OTAtNGQzOTQ3OTEtM2ZhOS00YjJmLTljMjgtOTkzNDEwOGEwYjBiLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhOTMzMmVkNzNkZTkzMmQxYTg3NjI0M2MxOTlkODkzOTBmMDJlOGQzOGJlYjI4MzYyMDcyMzA4NTQ3NWUwMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uVl-htjj2s2mXbo_PuIWeefiGSHeLrEJ80rxDFpAxfc"> <img alt="icon-attention" width="16" src="https://private-user-images.githubusercontent.com/12963621/374245590-4d394791-3fa9-4b2f-9c28-9934108a0b0b.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDU1OTAtNGQzOTQ3OTEtM2ZhOS00YjJmLTljMjgtOTkzNDEwOGEwYjBiLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhOTMzMmVkNzNkZTkzMmQxYTg3NjI0M2MxOTlkODkzOTBmMDJlOGQzOGJlYjI4MzYyMDcyMzA4NTQ3NWUwMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uVl-htjj2s2mXbo_PuIWeefiGSHeLrEJ80rxDFpAxfc"> <img alt="icon" width="64" src="https://private-user-images.githubusercontent.com/12963621/374245610-ff7b8091-5f22-4106-bee8-9197aff5a794.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDU2MTAtZmY3YjgwOTEtNWYyMi00MTA2LWJlZTgtOTE5N2FmZjVhNzk0LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMWUwNmY3MGM4YzAxN2JjYmE2ZGNjYjI5MWE3MWY2MGM2Y2IyMjM5NzIwZjc5NjA5ZmRmNjU4NmIyODNmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PQqvW1w9zRR2UouP34up9bS7MksnJKh_Vp_zVPlUwf8"> <img alt="icon" width="32" src="https://private-user-images.githubusercontent.com/12963621/374245610-ff7b8091-5f22-4106-bee8-9197aff5a794.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDU2MTAtZmY3YjgwOTEtNWYyMi00MTA2LWJlZTgtOTE5N2FmZjVhNzk0LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMWUwNmY3MGM4YzAxN2JjYmE2ZGNjYjI5MWE3MWY2MGM2Y2IyMjM5NzIwZjc5NjA5ZmRmNjU4NmIyODNmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PQqvW1w9zRR2UouP34up9bS7MksnJKh_Vp_zVPlUwf8"> <img alt="icon" width="16" src="https://private-user-images.githubusercontent.com/12963621/374245610-ff7b8091-5f22-4106-bee8-9197aff5a794.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDU2MTAtZmY3YjgwOTEtNWYyMi00MTA2LWJlZTgtOTE5N2FmZjVhNzk0LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMWUwNmY3MGM4YzAxN2JjYmE2ZGNjYjI5MWE3MWY2MGM2Y2IyMjM5NzIwZjc5NjA5ZmRmNjU4NmIyODNmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PQqvW1w9zRR2UouP34up9bS7MksnJKh_Vp_zVPlUwf8">
> 
> For reference, the original WhatsApp logo a same scale
> <img alt="WhatsApp" width="64" src="https://private-user-images.githubusercontent.com/12963621/374246266-dbba6f42-7e4e-4fc9-bc61-4895d49feae8.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDYyNjYtZGJiYTZmNDItN2U0ZS00ZmM5LWJjNjEtNDg5NWQ0OWZlYWU4LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZDRiMzM1YzIwYmI0MjU2YzkwODE1N2UxNmNmMTBlZDI2NGU4ODU4YTQxNmUwYjVkYjE2NTZkOTY3ODUzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.maCye0PgUpwbjnMZWM3rFzklIfHyMar2oH82mu8s76o"> <img alt="WhatsApp" width="32" src="https://private-user-images.githubusercontent.com/12963621/374246266-dbba6f42-7e4e-4fc9-bc61-4895d49feae8.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDYyNjYtZGJiYTZmNDItN2U0ZS00ZmM5LWJjNjEtNDg5NWQ0OWZlYWU4LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZDRiMzM1YzIwYmI0MjU2YzkwODE1N2UxNmNmMTBlZDI2NGU4ODU4YTQxNmUwYjVkYjE2NTZkOTY3ODUzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.maCye0PgUpwbjnMZWM3rFzklIfHyMar2oH82mu8s76o"> <img alt="WhatsApp" width="16" src="https://private-user-images.githubusercontent.com/12963621/374246266-dbba6f42-7e4e-4fc9-bc61-4895d49feae8.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjExMjAsIm5iZiI6MTcyOTE2MDgyMCwicGF0aCI6Ii8xMjk2MzYyMS8zNzQyNDYyNjYtZGJiYTZmNDItN2U0ZS00ZmM5LWJjNjEtNDg5NWQ0OWZlYWU4LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZDRiMzM1YzIwYmI0MjU2YzkwODE1N2UxNmNmMTBlZDI2NGU4ODU4YTQxNmUwYjVkYjE2NTZkOTY3ODUzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.maCye0PgUpwbjnMZWM3rFzklIfHyMar2oH82mu8s76o">
> 
> Feel free to use either (of the custom versions of course) at project license. I can push a PR replacing the current PNG version if desired.
> 
> (I am neither a designer nor a trademarks expert, just an attempt to maybe get some movement in here)

Thanks a lot! I will replace the icons soon or please feel free to create a PR.

**Comment by xeco23** [comment]
Atm snap and flatpak packages redirect to non-existent links. I'll create a new release soon with the new name. Then, the existing packages should slowly switch to that. I will take care of the snap migration but as said will not do anything about the flatpak. A new maintainer for the flatpak package is much appreciated.

**Comment by xeco23** [comment]
I also decided to stop maintaining snap because it's driving me mad...

**Comment by colonia-duck** [comment]
fair enough. 
I've migrated the Gentoo package to the new name.

**Comment by bbhtt** [comment]
> Anyone is welcome to submit a flatpak repo and maintain it. Please refer to the old repo: https://github.com/flathub/com.github.eneshecan.WhatsAppForLinux.

A new submission for Flathub is not needed. The ID is a technical detail and doesn't need to change. Only the user visible parts need to change `name` in metainfo, desktop file, icon etc. So resubmission is not needed.

Updating the old one to the new branding is enough. If anyone wants to do it, please open an issue on https://github.com/flathub/flathub

**Comment by bkanuka** [comment]
Thanks for renaming - I'm glad this project will continue to live.

But what's the reasoning for then name `WasIstLos` ? 😛   Does it mean something?  I don't even know how to pronounce it in my head!

(note, I'm not complaining - I'd be happy with anything)

**Edit: got it, it's German for "what's up" or "what's wrong".  Its a good name.  Es ist ein guter name.**
