### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by Sidethorn** [xeco23/WasIstLos#410]
When opening WA there is only the logo and nothing happens looks like it keeps on loading forever. Uninstalled and reinstalled again but nothing happens. 
Arch (tried both wayland and X) with gnome 47

**Comment by 3xploiton3** [comment]
bug relate to package webkit2gtk-imgpaste 2.46.0-1

try downgrade version

**Comment by rien333** [comment]
> bug relate to package webkit2gtk-imgpaste

Well, it's certainly related to webkit2gtk/webkit, cause it's also present in Gnome Web ("epiphany") and other webkitgtk apps. 

Related upstream issues: [https://bugs.webkit.org/show_bug.cgi?id=275890](https://bugs.webkit.org/show_bug.cgi?id=275890)

FWIW, I don't think there's anything this project can do here.

**Comment by jose1711** [comment]
> Did anyone solve this by downgrading ?

I did. Downgraded packages to the following versions:
```
webkit2gtk-4.1 2.44.4-1
libjxl 0.10.3-1
ffmpeg 2:7.0.2-2
```

**Comment by rien333** [comment]
Fixed on arch, after upgrading `webkit2gtk-4.1` and `webkit2gtk` to 2.46.1-1.  (here's the thread that mentions the fix: https://bugs.webkit.org/show_bug.cgi?id=275890)

**Comment by joske** [comment]
confirmed working on Arch as of today!

**Comment by tmelikoff** [comment]
For those running Debian 12 Cinnamon , the recent update of both `libwebkit2gtk-4.1-0` and `libjavascriptcoregtk-4.1-0` to version `2.46.0-2~deb12u1`, lead to the same issue (QR code not loading).

To solve, downgrade the related packages:
`apt install libwebkit2gtk-4.1-0=2.44.2-1~deb12u1 libjavascriptcoregtk-4.1-0=2.44.2-1~deb12u1`

I'll notify package maintainers of this regression.

Update: It has been already notified [here](https://alioth-lists.debian.net/pipermail/pkg-webkit-maintainers/2024-October/007377.html)
